### ISSUE TITLE
feature request: coin flip

### ISSUE THREAD

**Issue by Kovaelin** [JakeRunsDnD/tavernbot#50]
> !flip [n]

[n] is the (optional) number of flipped coins. The bot replies with the total number of heads and total number of tails. You may also want to specify a maximum number.

**Comment by JakeRunsDnD** [comment]
I like it! I already have a !coin implemented, so summing them up is just a parameter and a loop away. I'll try to get to this as soon as I've got some of the more pressing discord role stuff implemented

**Comment by JakeRunsDnD** [comment]
Got it. This is currently on the development branch, and once I get the rest of the Version 1.0 milestone done, I'll test it up and merge it to master before pushing it to NPM :)

Example output - I'll crank up the max coins to like 1000 before committing it though:
> d.coin()
'the botcoin landed on heads!'
> d.coin(1)
'the botcoin landed on heads!'
> d.coin(2)
'we flipped a total of 0 heads and 2 tails'
> d.coin(256)
'we flipped a total of 125 heads and 131 tails'
> d.coin(257)
'I literally don\'t have enough coins for that, looks like I only have about 250 in the piggy bank'
